### ISSUE TITLE
Aistudio 平台运行paddlemix下面的文生图例子出错

### ISSUE THREAD

**Issue by luoguangyao1987** [PaddlePaddle/PaddleMIX#242]
['OpenCC', 'CONFIGS', '__version__'] 10 __version__ = opencc_clib.__version__ ImportError: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/opencc/clib/opencc_clib.cpython-310-x86_64-linux-gnu.so)

**Comment by luoguangyao1987** [comment]
import paddle
from paddlemix.appflow import Appflow

paddle.seed(1024)
task = Appflow(app="text2image_generation",
               models=["stabilityai/stable-diffusion-v1-5"]
               )
prompt = "a photo of an astronaut riding a horse on mars."
result = task(prompt=prompt)['result']

**Comment by LokeZhou** [comment]
看着像aistudio环境的问题，起最新的aistudio环境试试

**Comment by Part-Work** [comment]
I have the same problem. I got this error message:

Error: Can not import paddle core while this file exists: /home/test/PaddleMIX/PMIX/lib/python3.8/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/home/test/PaddleMIX/Mana-Test.py", line 1, in <module>
    import paddle
  File "/home/test/PaddleMIX/PMIX/lib/python3.8/site-packages/paddle/__init__.py", line 30, in <module>
    from .base import core  # noqa: F401
  File "/home/test/PaddleMIX/PMIX/lib/python3.8/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/home/test/PaddleMIX/PMIX/lib/python3.8/site-packages/paddle/base/backward.py", line 25, in <module>
    from . import core, framework, log_helper, unique_name
  File "/home/test/PaddleMIX/PMIX/lib/python3.8/site-packages/paddle/base/core.py", line 383, in <module>
    raise e
  File "/home/test/PaddleMIX/PMIX/lib/python3.8/site-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/test/PaddleMIX/PMIX/lib/python3.8/site-packages/paddle/base/libpaddle.so)
