### ISSUE TITLE
ControlNet Reference Only这个社区实例无法运行，希望得到解决

### ISSUE THREAD

**Issue by intersoulest** [PaddlePaddle/PaddleMIX#248]
代码运行后报错
`Traceback (most recent call last):
  File "/disk2T/xxz/TextureRecommend/scripts/referrence.py", line 14, in <module>
    image = pipe(prompt,
  File "/home/xxz/.conda/envs/SD/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/xxz/.conda/envs/SD/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "/disk2T/xxz/TextureRecommend/scripts/reference_only.py", line 1111, in __call__
    noise_pred = self.unet(
  File "/home/xxz/.conda/envs/SD/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/xxz/.conda/envs/SD/lib/python3.10/site-packages/ppdiffusers/models/unet_2d_condition.py", line 931, in forward
    sample, res_samples = downsample_block(
  File "/home/xxz/.conda/envs/SD/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/xxz/.conda/envs/SD/lib/python3.10/site-packages/ppdiffusers/models/unet_2d_blocks.py", line 1036, in forward
    hidden_states = attn(
  File "/home/xxz/.conda/envs/SD/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
TypeError: transformer_2d_model_forward() got an unexpected keyword argument 'attention_mask'`
报错显示这个attention_mask参数有问题

**Comment by JunnYu** [comment]
你好，现在已经修复问题了，可以直接使用了
