### ISSUE TITLE
train_dreambooth_lora.py BAAI/AltDiffusion-m9 报错KeyError: 'XLMRobertaTokenizer' 

### ISSUE THREAD

**Issue by zouxiaodong** [PaddlePaddle/PaddleMIX#25]
使用如下脚本，训练BAAI/AltDiffusion-m9 LORA :

export MODEL_NAME="BAAI/AltDiffusion-m9"
export INSTANCE_DIR="dog"
export OUTPUT_DIR="alt-lora-model"

python train_dreambooth_lora.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="一张<鸣人>的图片" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --checkpointing_steps=100 \
  --learning_rate=1e-4 \
  --report_to="visualdl" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="一张<鸣人>在篮子里面的图片" \
  --validation_epochs=50 \
  --lora_rank=4 \
  --seed=0

详细错误如下：
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 564/564 [00:00<00:00, 2.49MB/s]
Traceback (most recent call last):
  File "/home/ai/robert/PaddleMIX/ppdiffusers/examples/dreambooth/train_dreambooth_lora.py", line 1158, in <module>
    main()
  File "/home/ai/robert/PaddleMIX/ppdiffusers/examples/dreambooth/train_dreambooth_lora.py", line 690, in main
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/ai/anaconda3/envs/paddlenlp/lib/python3.10/site-packages/paddlenlp/transformers/auto/tokenizer.py", line 363, in from_pretrained
    tokenizer_class = cls._get_tokenizer_class_from_config(
  File "/home/ai/anaconda3/envs/paddlenlp/lib/python3.10/site-packages/paddlenlp/transformers/auto/tokenizer.py", line 197, in _get_tokenizer_class_from_config
    class_name = cls._name_mapping[init_class]
KeyError: 'XLMRobertaTokenizer'

**Comment by westfish** [comment]
请参考https://github.com/PaddlePaddle/PaddleMIX/pull/32
