### ISSUE TITLE
Library version issue

### ISSUE THREAD

**Issue by Peachol** [PaddlePaddle/PaddleMIX#294]
When deploying SD, it was found that there was an issue with the environment. It seems that there is a compatibility issue between Paddle and Paddlenlp. The error log is as follows：
`Traceback (most recent call last):
  File "/data/dmx/sd_dir/ppdiffusers/examples/text_to_image_laion400m/train_txt2img_laion400m_trainer.py", line 19, in <module>
    from ldm import (
  File "/data/dmx/sd_dir/ppdiffusers/examples/text_to_image_laion400m/ldm/__init__.py", line 16, in <module>
    from .ldm_args import DataArguments, ModelArguments, NoTrainerTrainingArguments
  File "/data/dmx/sd_dir/ppdiffusers/examples/text_to_image_laion400m/ldm/ldm_args.py", line 20, in <module>
    from paddlenlp.utils.log import logger
  File "/home/dmx/miniconda3/envs/sd/lib/python3.9/site-packages/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/home/dmx/miniconda3/envs/sd/lib/python3.9/site-packages/paddlenlp/data/__init__.py", line 18, in <module>
    from .data_collator import *
  File "/home/dmx/miniconda3/envs/sd/lib/python3.9/site-packages/paddlenlp/data/data_collator.py", line 26, in <module>
    from ..transformers import BertTokenizer
  File "/home/dmx/miniconda3/envs/sd/lib/python3.9/site-packages/paddlenlp/transformers/__init__.py", line 17, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "/home/dmx/miniconda3/envs/sd/lib/python3.9/site-packages/paddlenlp/transformers/model_utils.py", line 62, in <module>
    from ..generation import GenerationConfig, GenerationMixin
  File "/home/dmx/miniconda3/envs/sd/lib/python3.9/site-packages/paddlenlp/generation/__init__.py", line 15, in <module>
    from .logits_process import (
  File "/home/dmx/miniconda3/envs/sd/lib/python3.9/site-packages/paddlenlp/generation/logits_process.py", line 22, in <module>
    from paddle.nn.layer.layers import in_declarative_mode
ModuleNotFoundError: No module named 'paddle.nn.layer.layers'
`

**Comment by JunnYu** [comment]
please upgrade your ppdiffusers 、paddlenlp and paddlepaddle version
ppdiffusers==0.19.3
paddlenlp==2.6.1
paddlepaddle-gpu==2.5.2
cuda>=11.2
