### ISSUE TITLE
【NVIDIA】当--use_ema True时，DiT单卡训练失败

### ISSUE THREAD

**Issue by yumin066** [PaddlePaddle/PaddleMIX#563]
使用
https://github.com/PaddlePaddle/PaddleMIX/blob/develop/ppdiffusers/examples/class_conditional_image_generation/DiT/0_run_train_dit_trainer.sh
脚本做单卡训练。

修改原脚本中的配置，如下：
```
19 TRAINING_GPUS_PER_NODE=1 # nproc_per_node
22 SHARDING_DEGREE=1 # sharding_parallel_degree
```
训练时报如下错误：
```
Traceback (most recent call last):
  File "/home/minyu/PaddleMIX/ppdiffusers/examples/class_conditional_image_generation/DiT/train_image_generation_trainer.py", line 142, in <module>
    main()
  File "/home/minyu/PaddleMIX/ppdiffusers/examples/class_conditional_image_generation/DiT/train_image_generation_trainer.py", line 119, in main
    trainer = LatentDiffusionTrainer(
  File "/home/minyu/PaddleMIX/ppdiffusers/examples/class_conditional_image_generation/DiT/diffusion/trainer.py", line 315, in __init__
    self.ema_callback = EmaCallback(kwargs["model"], decay=0.99)
  File "/home/minyu/PaddleMIX/ppdiffusers/examples/class_conditional_image_generation/DiT/diffusion/ema_callback.py", line 30, in __init__
    hcg = fleet.get_hybrid_communicate_group()
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/fleet/fleet.py", line 670, in get_hybrid_communicate_group
    assert self._hcg is not None
AttributeError: 'Fleet' object has no attribute '_hcg'
```

如果再将训练参数--user_ema设为False，
`73    --use_ema False \
`
则单卡训练能正常运行。

看起来像是ema的实现，没有考虑单卡训练的情况。

**Comment by westfish** [comment]
修复了，参考这个https://github.com/PaddlePaddle/PaddleMIX/pull/569
