### ISSUE TITLE
"_CudaDeviceProperties" is already registered

### ISSUE THREAD

**Issue by gongshichina** [PaddlePaddle/PaddleMIX#57]
运行示例代码会报错，看起来是因为同时引用了pd和torch
`import paddle`
`
from ppdiffusers import StableDiffusionPipeline
`

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/ppdiffusers/__init__.py", line 17, in <module>
    from . import patches
  File "/opt/conda/lib/python3.8/site-packages/ppdiffusers/patches/__init__.py", line 15, in <module>
    from . import ppnlp_patch_utils, tomesd_patch_utils, webui_lora_patch_utils
  File "/opt/conda/lib/python3.8/site-packages/ppdiffusers/patches/ppnlp_patch_utils.py", line 26, in <module>
    from ..utils import (
  File "/opt/conda/lib/python3.8/site-packages/ppdiffusers/utils/__init__.py", line 93, in <module>
    from .load_utils import is_torch_file, safetensors_load, smart_load, torch_load
  File "/opt/conda/lib/python3.8/site-packages/ppdiffusers/utils/load_utils.py", line 50, in <module>
    import torch
  File "/opt/conda/lib/python3.8/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
RuntimeError: generic_type: type "_CudaDeviceProperties" is already registered!

**Comment by Spencer2bN1** [comment]
同问，而且pd和torch选的都是CUDA11.8，也不行

**Comment by livingbody** [comment]
win11 下报错：
```
[2023-12-03 01:29:44,539] [ WARNING] - aistudio_download not import, if you want to use , require paddlenlp develop
Traceback (most recent call last):
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\main.py", line 29, in <module>
    from paddlemix.appflow import Appflow
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\paddlemix\appflow\__init__.py", line 15, in <module>
    from .appflow import Appflow
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\paddlemix\appflow\appflow.py", line 20, in <module>
    from .configuration import APPLICATIONS
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\paddlemix\appflow\configuration.py", line 15, in <module>
    from .image2image_text_guided_generation import (
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\paddlemix\appflow\image2image_text_guided_generation.py", line 15, in <module>
    from ppdiffusers import StableDiffusionImg2ImgPipeline, StableDiffusionUpscalePipeline
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\ppdiffusers\ppdiffusers\__init__.py", line 17, in <module>
    from . import patches
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\ppdiffusers\ppdiffusers\patches\__init__.py", line 15, in <module>
    from . import ppnlp_patch_utils, tomesd_patch_utils, webui_lora_patch_utils
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\ppdiffusers\ppdiffusers\patches\ppnlp_patch_utils.py", line 27, in <module>
    from ..utils import (
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\ppdiffusers\ppdiffusers\utils\__init__.py", line 98, in <module>
    from .load_utils import is_torch_file, safetensors_load, smart_load, torch_load
  File "C:\Users\jianj\PycharmProjects\pythonProject1\PaddleMIX\ppdiffusers\ppdiffusers\utils\load_utils.py", line 51, in <module>
    import torch
  File "I:\miniconda3\envs\p2\lib\site-packages\torch\__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
RuntimeError: generic_type: type "_CudaDeviceProperties" is already registered!

```

**Comment by LokeZhou** [comment]
请用当前最新的paddlemix试一下，同时保证cuda>=11.2

**Comment by flykitezero** [comment]
如果确定不需要torch，可以把环境中的torch卸载，单独使用paddle，就不会出现这个报错

**Comment by flymorn** [comment]
win10 同样错误：
[2024-08-10 12:51:10,862] [ WARNING] - Detected that datasets module was imported before paddlenlp. This may cause PaddleNLP datasets to be unavalible in intranet. Please import paddlenlp before datasets module to avoid download issues
W0810 12:51:11.861413 30240 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.7
W0810 12:51:11.864413 30240 gpu_resources.cc:164] device: 0, cuDNN Version: 8.6.
Traceback (most recent call last):
  File "3.py", line 1, in <module>
    from paddlemix.appflow import Appflow
  File "D:\Python\projects\PaddleMIX\PaddleMIX-2.0.0\paddlemix\__init__.py", line 17, in <module>
    from .models import *
  File "D:\Python\projects\PaddleMIX\PaddleMIX-2.0.0\paddlemix\models\__init__.py", line 17, in <module>
    from .audioldm2.modeling import *
  File "D:\Python\projects\PaddleMIX\PaddleMIX-2.0.0\paddlemix\models\audioldm2\modeling.py", line 25, in <module>
    from .latent_encoder.autoencoder import DiagonalGaussianDistribution
  File "D:\Python\projects\PaddleMIX\PaddleMIX-2.0.0\paddlemix\models\audioldm2\latent_encoder\autoencoder.py", line 18, in <module>
    from ppdiffusers import AutoencoderKL
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\__init__.py", line 17, in <module>
    from .patches import *
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\patches\__init__.py", line 14, in <module>
    from .converter import *
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\patches\converter.py", line 22, in <module>
    from ppdiffusers.transformers.model_utils import ModuleUtilsMixin
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\transformers\__init__.py", line 16, in <module>
    from .auto import *
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\transformers\auto\__init__.py", line 15, in <module>
    from .configuration import *
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\transformers\auto\configuration.py", line 24, in <module>
    from ..model_utils import PretrainedConfig, PretrainedModel
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\transformers\model_utils.py", line 30, in <module>
    from ppdiffusers.utils import (
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\utils\__init__.py", line 141, in <module>
    from .load_utils import is_torch_file, safetensors_load, smart_load, torch_load
  File "d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers\ppdiffusers\utils\load_utils.py", line 52, in <module>
    import torch
  File "C:\Program Files\Python38\lib\site-packages\torch\__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
RuntimeError: generic_type: type "_CudaDeviceProperties" is already registered!

环境：
paddle2onnx               1.0.6
paddlefsl                 1.1.0
paddlehub                 2.4.0
paddlemix                 0.1.0         D:\Python\projects\PaddleMIX\PaddleMIX-2.0.0
paddlenlp                 2.7.2         D:\Python\projects\PaddleNLP\PaddleNLP-2.7.2
paddlepaddle-gpu          2.6.1.post117
ppdiffusers               0.24.1        d:\python\projects\paddlemix\paddlemix-2.0.0\ppdiffusers
