### ISSUE TITLE
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name'

### ISSUE THREAD

**Issue by ZhijunLStudio** [PaddlePaddle/PaddleMIX#811]
sd3模型加载的时候报错huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'stabilityai/stable-diffusion-3-medium-diffusers/text_encoder_3'. Use `repo_type` argument if needed.

下面是相关代码
import paddle
from ppdiffusers import StableDiffusion3Pipeline
pipe = StableDiffusion3Pipeline.from_pretrained(
    "stabilityai/stable-diffusion-3-medium-diffusers", paddle_dtype=paddle.float16
)
generator = paddle.Generator().manual_seed(42)
prompt = "A cat holding a sign that says hello world"
image = pipe(prompt, generator=generator).images[0]
image.save("text_to_image_generation-stable_diffusion_3-result.png")

下面是相关包
paddlemix                 0.1.0            
ppdiffusers               0.29.0 
paddlenlp                 3.0.0b0.post0
huggingface-hub           0.23.0

以下是具体的报错信息
W1113 16:20:15.825760 50945 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 61 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1113 16:20:15.825991 50945 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 12.4, Runtime API Version: 11.4
W1113 16:20:15.830971 50945 gpu_resources.cc:164] device: 0, cuDNN Version: 8.7.
(…)sion-3-medium-diffusers/model_index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 889/889 [00:00<00:00, 36.7kB/s]
(…)iffusers/scheduler/scheduler_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 138/138 [00:00<00:00, 8.54kB/s]
(…)edium-diffusers/text_encoder/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 598/598 [00:00<00:00, 84.3kB/s]
[2024-11-13 16:20:24,484] [    INFO] - Loading configuration file /home/lizhijun/.cache/paddlenlp/ppdiffusers/stabilityai/stable-diffusion-3-medium-diffusers/text_encoder/config.json                                                        | 0.00/598 [00:00<?, ?B/s]
(…)diffusers/text_encoder/model.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 495M/495M [02:34<00:00, 3.19MB/s]
[2024-11-13 16:22:59,670] [    INFO] - Loading weights file from cache at /home/lizhijun/.cache/paddlenlp/ppdiffusers/stabilityai/stable-diffusion-3-medium-diffusers/text_encoder/model.safetensors█████████████████████████████████| 495M/495M [02:34<00:00, 3.07MB/s]
[2024-11-13 16:23:01,193] [    INFO] - Loaded weights file from disk, setting weights to model.
[2024-11-13 16:23:04,817] [    INFO] - All model checkpoint weights were used when initializing CLIPTextModelWithProjection.

[2024-11-13 16:23:04,819] [    INFO] - All the weights of CLIPTextModelWithProjection were initialized from the model checkpoint at stabilityai/stable-diffusion-3-medium-diffusers/text_encoder.
If your task is similar to the task the model of the checkpoint was trained on, you can already use CLIPTextModelWithProjection for predictions without further training.
(…)ium-diffusers/text_encoder_2/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 594/594 [00:00<00:00, 93.4kB/s]
[2024-11-13 16:23:04,971] [    INFO] - Loading configuration file /home/lizhijun/.cache/paddlenlp/ppdiffusers/stabilityai/stable-diffusion-3-medium-diffusers/text_encoder_2/config.json                                                      | 0.00/594 [00:00<?, ?B/s]
(…)ffusers/text_encoder_2/model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.78G/2.78G [13:56<00:00, 3.32MB/s]
[2024-11-13 16:37:01,438] [    INFO] - Loading weights file from cache at /home/lizhijun/.cache/paddlenlp/ppdiffusers/stabilityai/stable-diffusion-3-medium-diffusers/text_encoder_2/model.safetensors█████████████████████████████| 2.78G/2.78G [13:56<00:00, 3.98MB/s]
[2024-11-13 16:37:11,467] [    INFO] - Loaded weights file from disk, setting weights to model.
[2024-11-13 16:37:24,492] [    INFO] - All model checkpoint weights were used when initializing CLIPTextModelWithProjection.

[2024-11-13 16:37:24,493] [    INFO] - All the weights of CLIPTextModelWithProjection were initialized from the model checkpoint at stabilityai/stable-diffusion-3-medium-diffusers/text_encoder_2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use CLIPTextModelWithProjection for predictions without further training.
(…)um-diffusers/text_encoder_3//config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 748/748 [00:00<00:00, 105kB/s]
[2024-11-13 16:37:25,460] [    INFO] - Loading configuration file /home/lizhijun/.cache/paddlenlp/ppdiffusers/stabilityai/stable-diffusion-3-medium-diffusers/text_encoder_3/config.json                                                      | 0.00/748 [00:00<?, ?B/s]
(…)t_encoder_3/model.safetensors.index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20.0k/20.0k [00:00<00:00, 2.26MB/s]
[2024-11-13 16:37:25,576] [    INFO] - Loading weights file from cache at /home/lizhijun/.cache/paddlenlp/ppdiffusers/stabilityai/stable-diffusion-3-medium-diffusers/text_encoder_3/model.safetensors.index.json                           | 0.00/20.0k [00:00<?, ?B/s]
Loading pipeline components...:  33%|█████████████████████████████████████████████████████████████████▎                                                                                                                                  | 3/9 [17:01<34:03, 340.55s/it]
Traceback (most recent call last):
  File "/home/lizhijun/04.mix/PaddleMIX-2.1.0/sd3_infer.py", line 6, in <module>
    pipe = StableDiffusion3Pipeline.from_pretrained(
  File "/home/lizhijun/04.mix/paddlemix2.1.0/ppdiffusers/ppdiffusers/pipelines/pipeline_utils.py", line 1112, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/home/lizhijun/04.mix/paddlemix2.1.0/ppdiffusers/ppdiffusers/pipelines/pipeline_utils.py", line 416, in load_sub_model
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "/home/lizhijun/04.mix/paddlemix2.1.0/ppdiffusers/ppdiffusers/transformers/model_utils.py", line 355, in from_pretrained
    model = super().from_pretrained(
  File "/home/lizhijun/04.mix/paddlemix2.1.0/ppdiffusers/ppdiffusers/patches/paddle_patch.py", line 984, in new_from_pretrained
    return raw_from_pretrained(
  File "/home/lizhijun/anaconda3/envs/paddlex/lib/python3.9/site-packages/paddlenlp-3.0.0b0.post0-py3.9.egg/paddlenlp/transformers/model_utils.py", line 2213, in from_pretrained
    resolved_archive_file, resolved_sharded_files, sharded_metadata, is_sharded = cls._resolve_model_file_path(
  File "/home/lizhijun/anaconda3/envs/paddlex/lib/python3.9/site-packages/paddlenlp-3.0.0b0.post0-py3.9.egg/paddlenlp/transformers/model_utils.py", line 1673, in _resolve_model_file_path
    resolved_sharded_files, sharded_metadata = get_checkpoint_shard_files(
  File "/home/lizhijun/anaconda3/envs/paddlex/lib/python3.9/site-packages/paddlenlp-3.0.0b0.post0-py3.9.egg/paddlenlp/transformers/utils.py", line 679, in get_checkpoint_shard_files
    last_shard = try_to_load_from_cache(
  File "/home/lizhijun/anaconda3/envs/paddlex/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/lizhijun/anaconda3/envs/paddlex/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'stabilityai/stable-diffusion-3-medium-diffusers/text_encoder_3'. Use `repo_type` argument if needed.

**Comment by westfish** [comment]
https://github.com/PaddlePaddle/PaddleMIX/blob/668091c82b358a20430da95f3a81d1f0567e507e/ppdiffusers/requirements.txt#L1C1-L1C19

请更新paddlenlp版本

**Comment by ZhijunLStudio** [comment]
paddlenlp                 3.0.0b2.post20241113
ppdiffusers               0.29.0 
huggingface-hub           0.23.0
还是报这个错

**Comment by westfish** [comment]
rm -rf ~/.cache/paddlenlp/ppdiffusers/stabilityai/stable-diffusion-3-medium-diffusers

删除一下缓存，重新下载一下paddle权重，再试试看呢

**Comment by ZhijunLStudio** [comment]
删了，也还是不行

**Comment by whisky-12** [comment]
同样的问题 FileNotFoundError: [Errno 2] No such file or directory: '/home/aistudio/.cache/paddlenlp/ppdiffusers/tmpjj6nly3q' -> '/home/aistudio/.cache/paddlenlp/ppdiffusers/stabilityai/stable-diffusion-3-medium-diffusers/text_encoder/config.json'
